### ISSUE TITLE
Broken on my end

### ISSUE THREAD

**Issue by claymorwan** [lunar-os/ZenCss#2]
For some reason none of my elements are blurred, just transparent or solid

**Comment by lunar-os** [comment]
you will need micaforeveryone and if u want: dwmblurglass

**Comment by claymorwan** [comment]
O ok that make sense now, I'm not on windows, ig imma have to find a linux alternative to these 2, thanks :3

**Comment by lunar-os** [comment]
> O ok that make sense now, I'm not on windows, ig imma have to find a linux alternative to these 2, thanks :3

What WM/DE are u using. It will be a within a compositor with blur or for kde use kwin

**Comment by claymorwan** [comment]
> What WM/DE are u using. It will be a within a compositor with blur or for kde use kwin

I'm using KDE  on wayland, I do already have blur enabled in my setting tho

**Comment by lunar-os** [comment]
download kwin fork for plasma 6

**Comment by claymorwan** [comment]
Ye i already have that on installed
